#version 460 core

layout(local_size_x = 1) in;

const uint height = %H%;
const uint width= %W%;

layout(std430, binding = 0) buffer Input1 {
    double mat_1[height][width];
};

layout(std430, binding = 1) buffer Input2 {
    double mat_2[height][width];
};

layout(std430, binding = 2) buffer Output {
    double mat_out[height][width];
};


void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint idy = gl_GlobalInvocationID.y;
    mat_out[idx][idy] = mat_1[idx][idy] + mat_2[idx][idy];
}
